name: planta_tracker
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auto_size_text: ^3.0.0
  dropdown_button2: ^2.3.9
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter_animated_dialog: ^2.0.1
  flutter_bloc: ^8.1.5
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_secure_storage: ^9.2.1
  geolocator: ^12.0.0
  http: ^1.2.1
  image_picker: ^1.1.1
  ionicons: ^0.2.2
  latlong2: ^0.9.1
  otp_text_field: ^1.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  styled_text: ^8.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Nunito/Nunito-VariableFont_wght.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Black.ttf
        - asset: assets/fonts/Nunito/static/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito/static/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito/static/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-ExtraLight.ttf
        - asset: assets/fonts/Nunito/static/Nunito-ExtraLightItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Light.ttf
        - asset: assets/fonts/Nunito/static/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito/static/Nunito-MediumItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/static/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito/static/Nunito-SemiBoldItalic.ttf