name: planta_tracker
description: "A new Flutter project."
publish_to: "none"
version: 1.0.3

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dropdown_button2: ^2.3.9
  email_validator: ^3.0.0
  equatable: ^2.0.7
  exif: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_easyloading: ^3.0.5
  flutter_html: ^3.0.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_secure_storage: ^9.2.4
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  geolocator: ^12.0.0
  http: ^1.3.0
  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+23
  ionicons: ^0.2.2
  latlong2: ^0.9.1
  otp_text_field: ^1.1.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  provider: ^6.1.4
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  styled_text: ^8.1.0
  carousel_slider_plus: ^7.1.0
  flutter_debouncer: ^2.0.0
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  win32: ^5.12.0
  flutter_plugin_android_lifecycle: ^2.0.28
  url_launcher_android: ^6.3.16

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Nunito/Nunito-VariableFont_wght.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Black.ttf
        - asset: assets/fonts/Nunito/static/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito/static/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito/static/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-ExtraLight.ttf
        - asset: assets/fonts/Nunito/static/Nunito-ExtraLightItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Light.ttf
        - asset: assets/fonts/Nunito/static/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito/static/Nunito-MediumItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/static/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito/static/Nunito-SemiBoldItalic.ttf
